version: "3.7"

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
